CREATE TABLE BOOKS(
BookID INT PRIMARY KEY,
Title VARCHAR(20) NOT NULL,
Author VARCHAR(20) NOT NULL,
ISBN VARCHAR(20) NOT NULL,
Publisher VARCHAR(20) NOT NULL,
Year DATE NOT NULL,
CopiesAvailable VARCHAR(20) NOT NULL,
);

CREATE TABLE MEMBERS(
MemberID INT PRIMARY KEY,
FirstName Varchar(20) NOT NULL,
LastName Varchar(20) NOT NULL,
Email Varchar (30) NOT NULL,
PhoneNumber Varchar (15) NOT NULL,
MembershipDate DATE,
);

CREATE TABLE BORROWINGS(
BorrowingID INT PRIMARY KEY,
BookID INT,
MemberID INT,
BorrowDate DATE NOT NULL,
DueDate DATE NOT NULL,
ReturnDate DATE,
CONSTRAINT FK_BOK FOREIGN KEY (BookID) References BOOKS(BookID),
CONSTRAINT FK_MEM FOREIGN KEY (MemberID) References MEMBERS(MemberID),

);

CREATE TABLE USERS(
UserID INT PRIMARY KEY,
Username VARCHAR(20) NOT NULL,
Password VARCHAR(20) NOT NULL,
Role VARCHAR(10) NOT NULL,
);
SET IDENTITY_INSERT USERS ON;

INSERT INTO USERS (UserID, Username, Password, Role) VALUES (1,'admin', 'password123','Admin');
INSERT INTO USERS (UserID, Username, Password, Role) VALUES (2,'User', 'password456','Member');
INSERT INTO USERS (UserID, Username, Password, Role) VALUES (3,'User2', 'password789','Member');

SELECT * FROM USERS;
SELECT * FROM BORROWINGS;
SELECT * FROM BOOKS;

SET IDENTITY_INSERT MEMBERS ON;
SELECT * FROM MEMBERS;

ALTER TABLE MEMBERS ADD NewMemberID INT IDENTITY(1,1);
ALTER TABLE MEMBERS DROP COLUMN MemberID;
EXEC sp_rename 'MEMBERS.NewMemberID', 'MemberID', 'COLUMN';

ALTER TABLE BORROWINGS DROP CONSTRAINT FK_MEM;
ALTER TABLE BORROWINGS
ADD CONSTRAINT FK_MEMS FOREIGN KEY (MemberID) REFERENCES MEMBERS(MemberID);

ALTER TABLE BORROWINGS ADD NewBorrowingID INT IDENTITY(1,1);
ALTER TABLE BORROWINGS DROP COLUMN BorrowingID;
EXEC sp_rename 'BORROWINGS.NewBorrowingID', 'BorrowingID', 'COLUMN';

ALTER TABLE BOOKS ADD NewBookID INT IDENTITY(1,1);
ALTER TABLE BOOKS DROP COLUMN BookID;
EXEC sp_rename 'BOOKS.NewBookID', 'BookID', 'COLUMN';

ALTER TABLE BORROWINGS DROP CONSTRAINT FK_BOK;
ALTER TABLE BORROWINGS DROP CONSTRAINT FK_MEM;